module.exports = {
  actions: [
    'listArtifactsForRepo',
    'listJobsForWorkflowRun',
    'listOrgSecrets',
    'listRepoSecrets',
    'listRepoWorkflows',
    'listSelectedRepositoriesEnabledGithubActionsOrganization',
    'listSelfHostedRunnersForOrg',
    'listSelfHostedRunnersForRepo',
    'listWorkflowRunArtifacts',
    'listWorkflowRuns',
    'listWorkflowRunsForRepo'
  ],
  activity: [
    'listEventsForAuthenticatedUser',
    'listNotificationsForAuthenticatedUser',
    'listOrgEventsForAuthenticatedUser',
    'listPublicEvents',
    'listPublicEventsForRepoNetwork',
    'listPublicEventsForUser',
    'listPublicOrgEvents',
    'listReceivedEventsForUser',
    'listReceivedPublicEventsForUser',
    'listRepoEvents',
    'listRepoNotificationsForAuthenticatedUser',
    'listReposStarredByAuthenticatedUser',
    'listReposStarredByUser',
    'listReposWatchedByUser',
    'listStargazersForRepo',
    'listWatchedReposForAuthenticatedUser',
    'listWatchersForRepo'
  ],
  apps: [
    'listAccountsForPlan',
    'listAccountsForPlanStubbed',
    'listInstallationReposForAuthenticatedUser',
    'listInstallations',
    'listInstallationsForAuthenticatedUser',
    'listPlans',
    'listPlansStubbed',
    'listReposAccessibleToInstallation',
    'listSubscriptionsForAuthenticatedUser',
    'listSubscriptionsForAuthenticatedUserStubbed'
  ],
  checks: ['listAnnotations', 'listForRef', 'listForSuite', 'listSuitesForRef'],
  enterpriseAdmin: ['listSelectedOrganizationsEnabledGithubActionsEnterprise'],
  gists: [
    'list',
    'listComments',
    'listCommits',
    'listForUser',
    'listForks',
    'listPublic',
    'listStarred'
  ],
  git: ['listMatchingRefs'],
  issues: [
    'list',
    'listAssignees',
    'listComments',
    'listCommentsForRepo',
    'listEvents',
    'listEventsForRepo',
    'listEventsForTimeline',
    'listForAuthenticatedUser',
    'listForOrg',
    'listForRepo',
    'listLabelsForMilestone',
    'listLabelsForRepo',
    'listLabelsOnIssue',
    'listMilestones'
  ],
  licenses: ['getAllCommonlyUsed'],
  migrations: [
    'listForAuthenticatedUser',
    'listForOrg',
    'listReposForOrg',
    'listReposForUser'
  ],
  orgs: [
    'list',
    'listAppInstallations',
    'listForAuthenticatedUser',
    'listForUser',
    'listInvitationTeams',
    'listMembers',
    'listMembershipsForAuthenticatedUser',
    'listOutsideCollaborators',
    'listPendingInvitations',
    'listPublicMembers',
    'listWebhooks'
  ],
  projects: [
    'listCards',
    'listCollaborators',
    'listColumns',
    'listForOrg',
    'listForRepo',
    'listForUser'
  ],
  pulls: [
    'list',
    'listCommentsForReview',
    'listCommits',
    'listFiles',
    'listRequestedReviewers',
    'listReviewComments',
    'listReviewCommentsForRepo',
    'listReviews'
  ],
  reactions: [
    'listForCommitComment',
    'listForIssue',
    'listForIssueComment',
    'listForPullRequestReviewComment',
    'listForTeamDiscussionCommentInOrg',
    'listForTeamDiscussionInOrg'
  ],
  repos: [
    'listBranches',
    'listCollaborators',
    'listCommentsForCommit',
    'listCommitCommentsForRepo',
    'listCommitStatusesForRef',
    'listCommits',
    'listContributors',
    'listDeployKeys',
    'listDeploymentStatuses',
    'listDeployments',
    'listForAuthenticatedUser',
    'listForOrg',
    'listForUser',
    'listForks',
    'listInvitations',
    'listInvitationsForAuthenticatedUser',
    'listPagesBuilds',
    'listPullRequestsAssociatedWithCommit',
    'listReleaseAssets',
    'listReleases',
    'listTags',
    'listTeams',
    'listWebhooks'
  ],
  search: ['code', 'commits', 'issuesAndPullRequests', 'repos', 'users'],
  secretScanning: ['listAlertsForRepo'],
  teams: [
    'list',
    'listChildInOrg',
    'listDiscussionCommentsInOrg',
    'listDiscussionsInOrg',
    'listForAuthenticatedUser',
    'listMembersInOrg',
    'listPendingInvitationsInOrg',
    'listProjectsInOrg',
    'listReposInOrg'
  ],
  users: [
    'list',
    'listEmailsForAuthenticated',
    'listFollowedByAuthenticated',
    'listFollowersForAuthenticatedUser',
    'listFollowersForUser',
    'listFollowingForUser',
    'listGpgKeysForAuthenticated',
    'listGpgKeysForUser',
    'listPublicEmailsForAuthenticated',
    'listPublicKeysForUser',
    'listPublicSshKeysForAuthenticated'
  ]
}
